### ISSUE TITLE
Can't see play/pause button on the events page

### ISSUE THREAD

**Issue by bbinet** [erwindon/SaltGUI#331]
**Describe the bug**
As shown in the below screenshot, the play/pause button are not displayed for me on the events page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to events page
4. See missing play/pause buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/76281/100214192-ddf88a00-2f0f-11eb-9748-6b2f263057c9.png)

**Additional context**
I'm using Firefox browser: version 83.0 (64-bit)

**Comment by bbinet** [comment]
Same issue on Chromium browser: Version 83.0.4103.116

Also note that I'm using Debian Linux (Buster)

**Comment by bbinet** [comment]
I came across a similar issue on stackoverflow: 
https://stackoverflow.com/questions/47059852/black-medium-right-pointing-triangle-symbol-not-working-on-mac

So I probably don't have the right font installed on my system.
As SaltGUI is a web application, I think we should not require any specific font to be installed, but as explained in [APAD1 comment](https://stackoverflow.com/questions/47059852/black-medium-right-pointing-triangle-symbol-not-working-on-mac#comment81067399_47059852): "If you are going to use a symbol, it's best to load a library, such as Font Awesome, so that you don't have to rely on your users having the necessary font to support the symbol you are using."

@erwindon what do you think?

**Comment by erwindon** [comment]
interesting...

The button is indeed literally invisible. The button should be visible twice. Once at the top, and once in the bottom.
The text `press '' to begin` is visible. The button is in-line in that text as `&#x23F5;&#xFE0E;`. So it is actually there.

Luckily, I'm on Debian Buster as well here, except that I normally run my browser on the host machine.

I see almost the same thing:
![afbeelding](https://user-images.githubusercontent.com/3663742/100231558-7bab8380-2f27-11eb-94ec-e670350ef3dc.png)

2 defects are visible here:
1) the looking-glass should be the monochrome variation as requested in the HTML (that's the FE0E code)
2) the image for the start-button is missing. in my case, I get a visible alternative, so I can still use it. the pause-button is then  showed which again should have been in the monochrome variation.
![afbeelding](https://user-images.githubusercontent.com/3663742/100231954-fe344300-2f27-11eb-8899-1ac19c11e471.png)

I really like to use the unicode symbols as images are slow-loading, difficult-to-resize, etc. but the observed effect is obviously not intended.

Note that one problem was known: chrome on chromebook does not use the monochrome variation. since it was otherwise very usable, I just filed a defect with chrome(book) and left it at that.

I've just tried multiple notations to solve your issue:
* without FE0E (which would result always in colourful icons as well) --> no change
* written as js escape code \u23F5 instead of an html -code --> no change
so that does not seem to be a solution.

fontawesome is not a useable solution as it is either non-free; or it has a limit of 10K pageviews.
my predecessors urged me to minimise the number of libraries and to keep the software fully open/free.

23F5 (play button) was introduced in the year 2014, so that should not be considered leading-edge technology.

There are about 20 different non-ascii characters in use here. And only one is failing (I checked most).

good news...
we were not using the actual "play button (25B6)", but "Black Medium Right-Pointing Triangle (23F5)".
which at the time looked the same, but nicer, so I used that one.

I'll update this symbol to "play button 25B6" and keep everything else unchanged.
since that is also its function is is actually an improvement as well...

**Comment by erwindon** [comment]
Bruno,
I just committed+pushed that change on `master`.
Can you please verify it?

**Comment by bbinet** [comment]
@erwindon Yes, I can now see the "Play" icon, but I still can't see the "Search" and "Pause" icons.

**Comment by erwindon** [comment]
problem is that I am quite sure what I installed on my VM as that installation happened today, as before today it was an SSH-only vm...
let's compare the installations, starting with the fonts:
```
$ dpkg -l | awk '/fonts/ { print $2; }'
fonts-cantarell
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-droid-fallback
fonts-lato
fonts-liberation
fonts-liberation2
fonts-noto-color-emoji
fonts-noto-mono
fonts-opensymbol
fonts-quicksand
gsfonts
libwoff1:amd64
xfonts-100dpi
xfonts-75dpi
xfonts-base
xfonts-encodings
xfonts-scalable
xfonts-utils
```

just installed chromium (83). works very well with the new update. all icons are visible (though still not in monochrome).

I'm on the ESR version of firefox, which is included in Buster, and has version 78. How did you get up to "83.0 (64-bit)"?

**Comment by bbinet** [comment]
Here is my list:
```
$ dpkg -l | awk '/fonts/ { print $2; }'
fonts-crosextra-carlito
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-droid-fallback
fonts-font-awesome
fonts-freefont-ttf
fonts-lato
fonts-liberation
fonts-liberation2
fonts-linuxlibertine
fonts-mathjax
fonts-noto-color-emoji
fonts-noto-core
fonts-noto-mono
fonts-noto-ui-core
fonts-opensymbol
fonts-quicksand
fonts-roboto-slab
fonts-sil-gentium
fonts-sil-gentium-basic
gsfonts
libwoff1:amd64
xfonts-100dpi
xfonts-75dpi
xfonts-base
xfonts-encodings
xfonts-scalable
xfonts-utils
```

I'm also wondering if SaltGUI couldn't just embed a font which is known to include all required symbols, so that it will work everywhere, and the rendering will also be the same on any platform.

Maybe we can also use font subsetting to create a "saltgui-symbols" font, that would contain only the 20 non-ascii characters in use by SaltGUI?
[This project](https://github.com/filamentgroup/glyphhanger) seem to allow to subset web fonts, or there are also online applications to create font subsets.

**Comment by bbinet** [comment]
I'm not able to assign the issue back to you, I can only unassign me...

**Comment by erwindon** [comment]
Your suggestion about webfonts is quite useful. never used `@font-face` before, but it looks easy.
but it also brings back the problem of loading extra files which we tried to prevent using the fonts.
and now that I looked into the "noto" fonts, these should contain everything needed.

I have a more fundamental problem now: there is one system reported a "not working" (yours) and one system reported as "working" (mine). I did not make any special arrangements for this to get things working.
Are you able to test this on another machine first?

**Comment by bbinet** [comment]
I've just tested on another machine and it works.
I don't know what is wrong with the non-working machine: I've only installed firefox from firefox website to get the latest version (https://www.mozilla.org/en-US/firefox/linux/)
But anyway, Idon't you think it is better for SaltGUI to embed everyhing it needs, so that it renders the same everywhere?

**Comment by erwindon** [comment]
> [...]don't you think it is better for SaltGUI to embed every[t]hing it needs, so that it renders the same everywhere?
when this is a common problem, yes.
SaltGUI is typically used from a central location which is in relative good order (for minions that is a whole other story!).
besides your report, I have received no similar ones, and your report was due to a non-working machine.
so, I see no big reasons to introduce either local fonts or local images now.

on your other machine, can you please go back to older version 889e0d2943183e6ceefa0188b799745afe2ac77d (the one before the play-button change) and also try that? I might revert 35440b2d84d695c2b31a9948dcd7256a1489f494 because the previous character (⏵︎) better matches the pause character (⏸︎), even though (▶︎) is the official play-button.

**Comment by bbinet** [comment]
> > [...]don't you think it is better for SaltGUI to embed every[t]hing it needs, so that it renders the same everywhere?
> 
> when this is a common problem, yes.
> SaltGUI is typically used from a central location which is in relative good order (for minions that is a whole other story!).

But SaltGUI is a javascript client-side software, so it executes in the browser of the users machines, not on the salt-master itself: so it means that if a user don't have the required font installed on his machine, then SaltGUI won't be displayed correctly, which I consider to be a bug...
In my opinion, if a website uses a non standard symbol, it should not hope the user has the right font installed but it should provide it with the web application.
If embedding a font is an issue, why not just use 20 lightweight icons (or create a css sprite for these 20 icons)? 

> besides your report, I have received no similar ones, and your report was due to a non-working machine.

A non working machine?
No, there must be a misunderstanding: my machine is working properly on any website except those icons on SaltGUI.

> so, I see no big reasons to introduce either local fonts or local images now.

I think a good reason for that is to ensure SaltGUI will display the same everywhere (On may work machine, some icons don't display. On my home machine, all icons are displayed but are not very pretty. These icons will be different on every client machine, depending on the fonts that are installed on the system) and to avoid possible icon bug as I'm facing on my work machine. 
What do you fear by loading extra files like icons or custom web font?
All websites always load a lot of stuff: html, xhr, javascript, css, images, icons, fonts.
So loading 20 icons should be very lightweight compared to all these resources that are loaded anyway, so I don't really understand the issue here...

> on your other machine, can you please go back to older version [889e0d2](https://github.com/erwindon/SaltGUI/commit/889e0d2943183e6ceefa0188b799745afe2ac77d) (the one before the play-button change) and also try that? I might revert [35440b2](https://github.com/erwindon/SaltGUI/commit/35440b2d84d695c2b31a9948dcd7256a1489f494) because the previous character (⏵︎) better matches the pause character (⏸︎), even though (▶︎) is the official play-button.

Sure, I'll try that when I'll be back at home (my home machine was displaying correctly the SaltGUI icons).

**Comment by erwindon** [comment]
Debian 11 bullseye (with updated firefox) no longer shows this problem.
feel free to re-open (or re-create) this issue when there is a recent OS+BROWSER that still has problems.
